---
- debug:
    msg: "{{ ansible_facts['distribution'] }} e {{ ansible_facts['distribution_major_version'] }}"

- name: Install in ubuntu
  include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "20"
