---
# handlers file for ansible-role-hashicorp-install
- name: Enable consul systemd
  ansible.builtin.systemd:
    name: consul
    enabled: yes

- name: Enable vault systemd
  ansible.builtin.systemd:
    name: vault
    enabled: yes

- name: Enable consul-online systemd
  ansible.builtin.systemd:
    name: consul-online
    enabled: yes